version: '3'
services: 
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment: 
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "Egen12345"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
    ordermanagement-api:
        build: .
        ports:
            - "8080:80" 
    